services:
  - type: web
    name: playscore-convert
    env: python
    branch: main
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_DEBUG
        value: "0"
    healthCheckPath: /
    autoDeploy: true
